# ML 알고리즘은 문자열(카테고리형, 텍스트형) 자료형을 허용하지 않는다.

#### 레이블 인코딩
- 레이블 인코딩은 카테고리 feature를 숫자값으로 변환하는 것

In [2]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']

In [3]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [9]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [12]:
print('디코딩 원본 값:' ,encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### 원-핫 인코딩
- 원-핫 인코딩은 숫자값에 따라 가중치가 부여되어 모델이 제대로 학습되지 못하는 레이블 인코딩의 문제점을 해결하기 위한 인코딩 방식
- 피처 값의 유형에 따라 새로운 피처를 추가해 고유값에 해당하는 컬럼에만 1을 표시하고, 나머지는 0을 표시하는 방식
- 원핫인코더로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환되어야 하며, 입력값으로는 2차원 데이터가 필요
- 판다스에서는 get_dummies()함수 이용, 문자열 카테고리를 숫자형으로 변환할 필요없이, 바로 변환할 수 있어서 편리.

In [6]:
# 원핫 인코딩
from sklearn.preprocessing import OneHotEncoder
items =['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 차원
(8, 6)


In [14]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기','믹서','믹서']})
df.head()
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자랜지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

### 피처 스케일링과 정규화
- 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업을 피처 스케일링(feature scaling)이라고 함.
- 대표적인 방법으로는 표준화(standardization) & 정규화(Normalizaiton) - P124 수식 참고
- 표준화는 데잍 피처 각각이 평균이 0이고, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것을 의미
- 정규화는 서로 다른 피처의 크기를 통일(똑같은 단위로 변경)하기 위해 크기를 변환해주는 개념
A(0-100), B(0-100000)이라면, 동일한 크기 단위로 비교하기 위해 최소 0 ~ 최대 1의 값으로 변환하는 것
- 사이킷런의 Normalizer 모듈(정규화) 선형대수에서의 정규화 개념이 적용됐으며, 개별 벡터의 크기를 맞추기 위해 변환하는 것을 의미

In [3]:
from sklearn.datasets import load_iris
import pandas as pd
iris=load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


#### StandardScaler
- 개별 피처를 평균이 0, 분산이 1인 값으로 변환해줌(정규분포로 변환)
- SVM, Linear Regression, Logistic Regression는 데이터가 가우시안 분포를 가지고 있다고 가정하고
구현된 알고리즘이기 때문에 사전에 표준화를 적용해주는 것이 예측 성능 향상에 중요한 요소

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df_scaled.mean())
print("\feature들의 분산 값")
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
eature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler
- MinMaxScaler는 데이터값을 0과 1사이의 범위값으로 반환(음수가 있을 경우 -1에서 1값으로 변환)
- 데이터가 정규분퐈 아닌 경우 Min, Max scale을 적용해 볼 수 있다.

In [5]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최소 값')
print(iris_df_scaled.mean())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 학습 데이터와 테스트 데이터이 스케일링 변환시 유의점
- 가능하다면, 전체 데이터에 스케일링을 적용한 뒤, 학습 데이터, 테스트 데이터로 분리
- 스케일링 시, 학습데이터 세트에 fit(), transform()을 적용하면 테스트데이터 세트에는 fit()을 적용하지 말아야한다.
- 테스트데이터 세트에 다시 fit()을 수행하게 되면, 새로운 스케일링 기준 정보를 만들게 되어,
- 학습데이터와 테스트데이터의 스케일링 기준 정보가 서로 달라지기 때문에 올바른 예측 결과를 도출하지 못함.