In [ ]:
판다스
판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

Contents

Series(변환, 인덱스 구조, 원소 선택)
DataFrame(변환, 행인덱스/열이름 지정, 삭제,선택,추가, 변경, 전치, 인덱스 활용)

In [83]:
# 시리즈 클래스 만들기
import pandas as pd

dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)
sr

a    1
b    2
c    3
dtype: int64

In [2]:
sr

a    1
b    2
c    3
dtype: int64

In [3]:
print(type(sr))

<class 'pandas.core.series.Series'>


In [6]:
# 리스트를 시리즈로 변환

list_data = ['2019-01-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data, index = ['a', 'b', 'c', 'd', 'e'])
sr

a    2019-01-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [7]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-01-02' 3.14 'ABC' 100 True]


In [86]:
# 튜플을 시리즈로 변환
tup_data = ('영인', '2015-05-01', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
sr

이름              영인
생년월일    2015-05-01
성별               여
학생여부          True
dtype: object

In [87]:
# 인덱싱
print(sr[0])
print(sr['이름'])

영인
영인


In [88]:
# 대괄호 []안에 인덱스를 리스트 형태로 입력하면 원소 데이터를 모두 반환
print(sr[[1,2]])

생년월일    2015-05-01
성별               여
dtype: object


In [91]:
import numpy as np

s1 = np.arange(11,16)
s2 = pd.Series(s1, index=['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [92]:
s2[1:3]

ED2    12
ED3    13
dtype: int32

In [93]:
data = np.arange(1000, 5000, 1000)
obj = pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index = state
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [95]:
#null(결측값) 대체
obj.california = np.nan
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [102]:
# null 화인
obj.isnull().sum()

0

In [ ]:
데이터프레임
데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
데이터프레임의 열은 각각 시리즈 개체.
시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 
같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [103]:
# 배열을 데이터프레임으로 변환
data = np.random.randint(100,120,size=(3,3))
print(data,type(data))

df = pd.DataFrame(data, index =['d1','d2','d3'],
                 columns = ['pd','sales','int'])
df

[[105 103 119]
 [101 113 104]
 [102 110 113]] <class 'numpy.ndarray'>


pd  sales  int
d1  105    103  119
d2  101    113  104
d3  102    110  113

In [109]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1],'\n') 
print(df.loc['d1'])

pd       101
sales    113
int      104
Name: d2, dtype: int64 

pd       105
sales    103
int      119
Name: d1, dtype: int64


In [113]:
# 행,열 추가
df.loc['d5'] = 0
df.loc['d1'] = 10 #이름 색인
df.iloc[2] = 5 #정수색인

In [114]:
df

pd  sales  int
d1   10     10   10
d2  101    113  104
d3    5      5    5
d5    0      0    0

In [116]:
# 원소 값 변경
df.iloc[1,1] = np.nan
df.iloc[2,2] = 0

df

pd  sales  int
d1   10   10.0   10
d2  101    NaN  104
d3    5    5.0    0
d5    0    0.0    0

In [117]:
import numpy as np
import pandas as pd

id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,81,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)
pdt_19 = np.random.randint(1, 6,size=1000)
p_19 = pd.Series(pdt_19)
pdt_20 = np.random.randint(1, 6,size=1000)
p_20 = pd.Series(pdt_20)
price_avg_19 = np.random.rand(1000)
pr19 = price_avg_19*10000
pa_19 = pd.Series(pr19)
price_avg_20 = np.random.rand(1000)
pr20 = price_avg_20*10000
pa_20 = pd.Series(pr20)
qty_19 = np.random.randint(1,101, 1000)
q_19 = pd.Series(qty_19)
qty_20 = np.random.randint(1,101, 1000)
q_20 = pd.Series(qty_20)
time_19 = np.random.randint(1, 24, 1000)
t_19 = pd.Series(time_19)
time_20 = np.random.randint(1, 24, 1000)
t_20 = pd.Series(time_20)
df = pd.concat([i1, g1,a1,r1,p_19,p_20,pa_19,pa_20,q_19,q_20,t_19,t_20],axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region',4:'pdt_19',5:'pdt_20',6:'pa_19',7:'pa_20',\
                  8:'q_19',9:'q_20',10:'t_19',11:'t_20'},inplace=True)
df['pa_19'] = round(df['pa_19'],2)
df['pa_20'] = round(df['pa_20'],2)
df.iloc[0,1] = np.nan
print(type(pa_19))
df.head()

<class 'pandas.core.series.Series'>


id  gender  age  region  pdt_19  pdt_20    pa_19    pa_20  q_19  q_20  \
0   1     NaN   34       3       2       4  9739.79  8375.31    63    11   
1   2     1.0    1      10       1       3  4491.98  8130.11    68    32   
2   3     1.0   26       3       3       4  2046.67  7665.33    73    20   
3   4     1.0   72       8       2       1  9700.78  6376.04    71    20   
4   5     1.0   11       5       2       1   449.09  5720.78    52    83   

   t_19  t_20  
0    17    14  
1    10     1  
2    11     1  
3     9    22  
4    16    22

In [118]:
df1 = df[:]
df1.head()

id  gender  age  region  pdt_19  pdt_20    pa_19    pa_20  q_19  q_20  \
0   1     NaN   34       3       2       4  9739.79  8375.31    63    11   
1   2     1.0    1      10       1       3  4491.98  8130.11    68    32   
2   3     1.0   26       3       3       4  2046.67  7665.33    73    20   
3   4     1.0   72       8       2       1  9700.78  6376.04    71    20   
4   5     1.0   11       5       2       1   449.09  5720.78    52    83   

   t_19  t_20  
0    17    14  
1    10     1  
2    11     1  
3     9    22  
4    16    22

In [119]:
df1.iloc[:5] = np.nan
df1.head(7)

id  gender   age  region  pdt_19  pdt_20    pa_19    pa_20  q_19  q_20  \
0  NaN     NaN   NaN     NaN     NaN     NaN      NaN      NaN   NaN   NaN   
1  NaN     NaN   NaN     NaN     NaN     NaN      NaN      NaN   NaN   NaN   
2  NaN     NaN   NaN     NaN     NaN     NaN      NaN      NaN   NaN   NaN   
3  NaN     NaN   NaN     NaN     NaN     NaN      NaN      NaN   NaN   NaN   
4  NaN     NaN   NaN     NaN     NaN     NaN      NaN      NaN   NaN   NaN   
5  6.0     0.0  51.0     3.0     5.0     2.0  1490.11  3264.64  85.0  22.0   
6  7.0     1.0  44.0     4.0     5.0     5.0  8730.46  9605.23  69.0  43.0   

   t_19  t_20  
0   NaN   NaN  
1   NaN   NaN  
2   NaN   NaN  
3   NaN   NaN  
4   NaN   NaN  
5  12.0  10.0  
6  16.0  20.0

In [120]:
# 사전을 데이터프레임으로 변환
sample_array = np.arange(5)
sample_df = pd.DataFrame({
    'col1':sample_array,
    'col2':sample_array*2,
    'col3':['A','B','C','D','E']
})
sample_df

col1  col2 col3
0     0     0    A
1     1     2    B
2     2     4    C
3     3     6    D
4     4     8    E

In [122]:
# 2차원 리스트를 데이터프레임으로 변환
a = np.random.randint(1,5,size=(10,5))
print(a)
list1 = a.tolist()
print(list1)
df = pd.DataFrame(list1, columns = ['c1','c2','c3','c4','c5'])
print(df)

[[4 2 1 4 3]
 [3 3 1 1 3]
 [1 2 2 1 4]
 [3 4 4 3 3]
 [4 1 4 4 3]
 [1 3 1 4 4]
 [2 3 3 4 2]
 [1 3 4 4 2]
 [4 2 2 1 2]
 [2 1 1 1 3]]
[[4, 2, 1, 4, 3], [3, 3, 1, 1, 3], [1, 2, 2, 1, 4], [3, 4, 4, 3, 3], [4, 1, 4, 4, 3], [1, 3, 1, 4, 4], [2, 3, 3, 4, 2], [1, 3, 4, 4, 2], [4, 2, 2, 1, 2], [2, 1, 1, 1, 3]]
   c1  c2  c3  c4  c5
0   4   2   1   4   3
1   3   3   1   1   3
2   1   2   2   1   4
3   3   4   4   3   3
4   4   1   4   4   3
5   1   3   1   4   4
6   2   3   3   4   2
7   1   3   4   4   2
8   4   2   2   1   2
9   2   1   1   1   3


In [123]:
# value_counts 함수 : 칼럼내 value별로 개수를 반환
print(type(df.c1.value_counts()))
df.c1.value_counts()

<class 'pandas.core.series.Series'>


4    3
1    3
3    2
2    2
Name: c1, dtype: int64

In [124]:
# unique 함수 : 칼럼내 unique한 value만을 반환
df.c1.unique()

array([4, 3, 1, 2], dtype=int64)

In [125]:
ar = df.values
print(ar,type(ar))

[[4 2 1 4 3]
 [3 3 1 1 3]
 [1 2 2 1 4]
 [3 4 4 3 3]
 [4 1 4 4 3]
 [1 3 1 4 4]
 [2 3 3 4 2]
 [1 3 4 4 2]
 [4 2 2 1 2]
 [2 1 1 1 3]] <class 'numpy.ndarray'>


In [126]:
li = df.values.tolist()
print(li,type(li))

[[4, 2, 1, 4, 3], [3, 3, 1, 1, 3], [1, 2, 2, 1, 4], [3, 4, 4, 3, 3], [4, 1, 4, 4, 3], [1, 3, 1, 4, 4], [2, 3, 3, 4, 2], [1, 3, 4, 4, 2], [4, 2, 2, 1, 2], [2, 1, 1, 1, 3]] <class 'list'>


In [127]:
dict = df.to_dict('list')
print(dict,type(dict))

{'c1': [4, 3, 1, 3, 4, 1, 2, 1, 4, 2], 'c2': [2, 3, 2, 4, 1, 3, 3, 3, 2, 1], 'c3': [1, 1, 2, 4, 4, 1, 3, 4, 2, 1], 'c4': [4, 1, 1, 3, 4, 4, 4, 4, 1, 1], 'c5': [3, 3, 4, 3, 3, 4, 2, 2, 2, 3]} <class 'dict'>


In [23]:
# 데이터프레임을 배열, 리스트, 사전으로 변환
print(df)

           id    gender       age    region   prod_19   prod_20  price_avg_19  \
0         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
1         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
2         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
3         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
4         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
..        ...       ...       ...       ...       ...       ...           ...   
995  0.602230  0.289449  0.833017  0.674893  0.103532  0.221028      0.022066   
996  0.875189  0.065846  0.632303  0.937630  0.933304  0.265567      0.056586   
997  0.792586  0.016119  0.550546  0.147306  0.815848  0.879809      0.915910   
998  0.967483  0.772697  0.770499  0.262272  0.134060  0.534579      0.447743   
999  0.476784  0.501249  0.623390  0.463050  0.677768  0.048268      0.084487   

     price_avg_20    qty_19

In [24]:
# file 생성
file_data = pd.DataFrame({
    'col1' : [1,2,3,4,5,6],
    'col2' : ['a','a','b','b','c','c']
})

file_data

col1 col2
0     1    a
1     2    a
2     3    b
3     4    b
4     5    c
5     6    c

In [26]:
file_data.to_csv('C:/caba2012/workspace/Caba_python/dataset/file_data.csv', index=None)

In [27]:
file_data = pd.read_csv('C:/caba2012/workspace/Caba_python/dataset/file_data.csv')

In [28]:
file_data

col1 col2
0     1    a
1     2    a
2     3    b
3     4    b
4     5    c
5     6    c

In [128]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1,'\n')
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C 

   col1 col2
0     4    D
1     5    E
2     6    F


In [129]:
# 병합 - 세로 방향
print(pd.concat([df_1,df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [130]:
# 병합 - 가로 방향
print(pd.concat([df_1,df_2], axis=1))

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [133]:
sample_array = np.arange(5)
sample_df =pd.DataFrame({
    'col1': sample_array,
    'col2': sample_array*2,
    'col3': ['A','B', 'C', 'D', 'E']
    
})

sample_df

col1  col2 col3
0     0     0    A
1     1     2    B
2     2     4    C
3     3     6    D
4     4     8    E

In [132]:
sample_df.col2
sample_df['col2']

0    0
1    2
2    4
3    6
4    8
Name: col2, dtype: int32

In [ ]:
# 과제
# 인덱싱으로 5개 데이터 뽑기

In [134]:
sample_df.iloc[2,2]

'C'

In [139]:
sample_df.loc[2, ['col1', 'col2']]

col1    2
col2    4
Name: 2, dtype: object

In [141]:
sample_df.loc[1, ['col1', 'col2', 'col3']]

col1    1
col2    2
col3    B
Name: 1, dtype: object

In [143]:
sample_df.loc[ :, ['col2', 'col3']]

col2 col3
0     0    A
1     2    B
2     4    C
3     6    D
4     8    E

In [34]:
sample_df

col1  col2 col3
0     0     0    a
1     1     2    b
2     2     4    c
3     3     6    d
4     4     8    e

In [144]:
#'col1':'col2'는 'col1'에서 'col2' 까지 포함
sample_df.loc[:,'col1':'col2']

col1  col2
0     0     0
1     1     2
2     2     4
3     3     6
4     4     8

In [41]:
sample_df[['col1', 'col3']]

col1 col3
0     0    a
1     1    b
2     2    c
3     3    d
4     4    e

In [145]:
sample_df.iloc[2,:]

col1    2
col2    4
col3    C
Name: 2, dtype: object

In [146]:
sample_df.iloc[2,1]

4

In [147]:
sample_df.loc[3:4,'col1':'col2']

col1  col2
3     3     6
4     4     8

In [45]:
sample_df

col1  col2 col3
0     0     0    a
1     1     2    b
2     2     4    c
3     3     6    d
4     4     8    e

In [47]:
# 열 삭제 
#inplace True: 데이터의 변형된 내용을 원본에 반영, False면 원본에 반영되지 않음
print(sample_df.drop('col1', axis=1, inplace=True))

None


In [148]:
print(sample_df.query('index==0')) #true로 반영하니까 col1이 없어진채 작업진행

   col1  col2 col3
0     0     0    A


In [149]:
# col3 열에서 값이 A인 행
print(sample_df.query('col3 == "A"'))

   col1  col2 col3
0     0     0    A


In [150]:
# 복수의 조건 - or
print(sample_df.query('col3 == "A" | col3=="D"'))

   col1  col2 col3
0     0     0    A
3     3     6    D


In [153]:
# 복수의 조건 - and
print(sample_df.query('col3 == "A" & col1 == 3'))

Empty DataFrame
Columns: [col1, col2, col3]
Index: []


In [154]:
#행, 열 모두에 조건 지정
print(sample_df.query('col3 == "A"')[['col2', 'col3']])

   col2 col3
0     0    A


In [57]:
sample_df[['col2', 'col3']]

col2 col3
0     0    a
1     2    b
2     4    c
3     6    d
4     8    e

In [155]:
# 데이터프레임에서 1열만 추출하면 시리즈로 변환
print(sample_df.col1)
type(sample_df.col1)

0    0
1    1
2    2
3    3
4    4
Name: col1, dtype: int32


pandas.core.series.Series

In [156]:
# 배열로 변환
np.array(sample_df.col1)

array([0, 1, 2, 3, 4])

In [157]:
sample_df.col1.values

array([0, 1, 2, 3, 4])

In [158]:
# Series로 데이터프레임 생성(배열 > Series > DataFrame)
import numpy as np
import pandas as pd
c0 = np.random.randint(60,100,size=(3,))
c1 = np.random.randint(60,100,size=(3,))
c2 = np.random.randint(60,100,size=(3,))
c3 = np.random.randint(60,100,size=(3,))
c4 = np.random.randint(60,100,size=(3,))
s1 = pd.Series(c0)
s2 = pd.Series(c1)
s3 = pd.Series(c2)
s4 = pd.Series(c3)
s5 = pd.Series(c4)
df = pd.concat([s1,s2,s3,s4,s5], axis=1)
df.columns=['kor','eng','sci','math','mus']
df.index = ['jim','sam','tom']
df

kor  eng  sci  math  mus
jim   67   83   65    60   76
sam   80   90   66    67   94
tom   61   76   93    85   85

In [159]:
data = np.random.randint(50,100,size=(3,5))
df = pd.DataFrame(data,columns=['kor','eng','sci','math','mus'],
                 index=['jim','sam','tom'])
df

kor  eng  sci  math  mus
jim   72   92   92    50   97
sam   89   63   92    61   98
tom   76   70   51    54   63

In [160]:
# 복사
df1 = df[:]
df1

kor  eng  sci  math  mus
jim   72   92   92    50   97
sam   89   63   92    61   98
tom   76   70   51    54   63

In [ ]:
# Q. df1에서 행 인덱스, 열 이름을 변경하여 아래와 같이 출력 하세요.     
열이름 : 국어, 영어, 과학, 수학, 음악
행이름 : j, s, t

In [161]:
df1.rename(columns={'kor':'국어','eng':'영어','sci':'과학','math':'수학','mus':'음악'},
          index = {'jim':'j','sam':'s','tom':'t'},inplace=True)
df1

국어  영어  과학  수학  음악
j  72  92  92  50  97
s  89  63  92  61  98
t  76  70  51  54  63

In [162]:
df1.index=['j','s','t']
df1.columns=['국어','영어','과학','수학','음악']
df1

국어  영어  과학  수학  음악
j  72  92  92  50  97
s  89  63  92  61  98
t  76  70  51  54  63

In [163]:
df1.iloc[0,4]
df1.loc['j','음악']

97

In [ ]:
# Q. 음악 칼럼, t행을 삭제해 보세요

In [164]:
df1.drop('음악',axis=1,inplace=True)
df1.drop('t',axis=0,inplace=True)
df1

국어  영어  과학  수학
j  72  92  92  50
s  89  63  92  61

In [ ]:
[과제]
# Q. 데이터프레임 df를 복제하여 df2로 저장한 후 
# df2의 2개 열(column) 'eng', 'mus'를 삭제하세요.

In [67]:
array{[62,83,72,77,86], [62,60,60,76,60], [90,63,91,91,64]}

SyntaxError: invalid syntax (<ipython-input-67-7fdd46a6742e>, line 1)

In [68]:
# 복사
df1 = df[:]
df1

id    gender       age    region   prod_19   prod_20  price_avg_19  \
0         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
1         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
2         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
3         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
4         NaN       NaN       NaN       NaN       NaN       NaN           NaN   
..        ...       ...       ...       ...       ...       ...           ...   
995  0.602230  0.289449  0.833017  0.674893  0.103532  0.221028      0.022066   
996  0.875189  0.065846  0.632303  0.937630  0.933304  0.265567      0.056586   
997  0.792586  0.016119  0.550546  0.147306  0.815848  0.879809      0.915910   
998  0.967483  0.772697  0.770499  0.262272  0.134060  0.534579      0.447743   
999  0.476784  0.501249  0.623390  0.463050  0.677768  0.048268      0.084487   

     price_avg_20    qty_19    qty_20   time_19   time_20  
0             NaN       NaN       NaN       NaN       NaN  
1             NaN       NaN       NaN       NaN       NaN  
2             NaN       NaN       NaN       NaN       NaN  
3             NaN       NaN       NaN       NaN       NaN  
4             NaN       NaN       NaN       NaN       NaN  
..            ...       ...       ...       ...       ...  
995      0.522117  0.657605  0.916682  0.088317  0.025437  
996      0.190487  0.319416  0.658333  0.902477  0.781800  
997      0.453962  0.264304  0.898581  0.609583  0.928028  
998      0.257782  0.169053  0.581260  0.043480  0.185458  
999      0.417152  0.083648  0.406745  0.126905  0.076982  

[1000 rows x 12 columns]

In [ ]:
# Q.df1에서 행 인덱스, 열 이름을 변경하여 아래와 같이 출력하세요.

In [69]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [77]:
df_af = titanic.loc[:, ['age', 'fare']]
df_af.head()

def mul_100(n):
    return n * 100

df_map = df_af.applymap(mul_100)
df_map.head()

age     fare
0  2200.0   725.00
1  3800.0  7128.33
2  2600.0   792.50
3  3500.0  5310.00
4  3500.0   805.00

In [80]:
round(titanic.fare,2)

0       7.25
1      71.28
2       7.92
3      53.10
4       8.05
       ...  
886    13.00
887    30.00
888    23.45
889    30.00
890     7.75
Name: fare, Length: 891, dtype: float64

In [81]:
titanic.shape

(891, 15)

In [82]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [73]:
df.loc[6]

survived                 0
pclass                   1
sex                   male
age                     54
sibsp                    0
parch                    0
fare               51.8625
embarked                 S
class                First
who                    man
adult_male            True
deck                     E
embark_town    Southampton
alive                   no
alone                 True
Name: 6, dtype: object